name: Continuous Integration & Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build workspaces
        run: npm run build --workspaces --if-present
      - name: Archive builds
        uses: actions/upload-artifact@v4
        with:
          name: builds
          retention-days: 1
          path: |
            apps/**/dist
            libs/**/**/dist
  lint:
    name: Static analysis
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint all workspaces
        run: npm run lint --workspaces
  test:
    name: Tests execution
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download builds
        uses: actions/download-artifact@v4
        with:
          name: builds
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test all workspaces
        run: npm run test --workspaces --if-present
